export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
  "Andaman and Nicobar Islands",
] as const;

export const LANGUAGES = [
  "Hindi",
  "English",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Urdu",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Odia",
  "Punjabi",
  "Assamese",
  "Maithili",
  "Sanskrit",
  "Konkani",
  "Nepali",
  "Manipuri",
  "Sindhi",
  "Dogri",
  "Kashmiri",
  "Bodo",
  "Santali",
  "Bhojpuri",
  "Rajasthani",
  "Tulu",
  "Chhattisgarhi",
  "Haryanvi",
] as const;

export const CONTENT_LANGUAGES = [
  "hindi",
  "english",
  "bengali",
  "telugu",
  "marathi",
  "tamil",
  "urdu",
  "gujarati",
  "kannada",
  "malayalam",
  "odia",
  "punjabi",
  "assamese",
  "bhojpuri",
  "rajasthani",
  "haryanvi",
  "tulu",
] as const;

export const BUSINESS_TYPES = [
  "Proprietorship",
  "Partnership",
  "LLP (Limited Liability Partnership)",
  "Private Limited",
  "Public Limited",
  "One Person Company (OPC)",
  "HUF (Hindu Undivided Family)",
  "Trust",
  "Society",
  "Section 8 Company",
] as const;

export const ANNUAL_TURNOVER_RANGES = [
  "Below ₹10 Lakhs",
  "₹10 Lakhs - ₹50 Lakhs",
  "₹50 Lakhs - ₹1 Crore",
  "₹1 Crore - ₹5 Crore",
  "₹5 Crore - ₹10 Crore",
  "₹10 Crore - ₹25 Crore",
  "₹25 Crore - ₹50 Crore",
  "₹50 Crore - ₹100 Crore",
  "Above ₹100 Crore",
] as const;

export const BANK_ACCOUNT_TYPES = [
  "Current",
  "Savings",
] as const;
